import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";

import { Toaster } from "@/components/ui/sonner";

import TopHeader from "@/components/top-header/top-header";
import Footer from "@/components/footer/footer";
import StoreProvider from "@/store/provider";
import { cookies } from "next/headers";
import { getCurrentUser } from "@/lib/auth";
import { BreadcrumbCustom } from "@/components/breadcrumb/breadcrumb-custom";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = cookies();
  const token = (await cookie)?.get("auth_token")?.value;
  let preLoadedUser = null;
  if (token) {
     preLoadedUser = await getCurrentUser(token);
  }
  return (
    <html lang="en">
      <body className={`antialiased  ${poppins.className}`}>
        <StoreProvider preLoadedUser={preLoadedUser}>
          <TopHeader />
          <Toaster richColors />
          <div className="w-full flex justify-center items-center">
            <div className="w-full max-w-[1200px]">
              {/* <BreadcrumbCustom /> */}
              {children}
            </div>
          </div>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
